# Generated by Django 5.2.7 on 2025-10-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
